// JWT verification middleware using Supabase Auth

import { Request, Response, NextFunction } from 'express';
import { supabase } from '../services/supabase.js';
import { AuthenticationError } from '../types/index.js';
import { logger } from '../config/logger.js';

// Extend Request type to include user
declare global {
  namespace Express {
    interface Request {
      user?: {
        id: string;
        email?: string;
      };
      userId?: string;
    }
  }
}

/**
 * Middleware to verify JWT token from Authorization header
 * Extracts user information and attaches it to the request object
 */
export async function verifyToken(
  req: Request,
  res: Response,
  next: NextFunction
): Promise<void> {
  try {
    // Extract token from Authorization header
    const authHeader = req.headers.authorization;

    if (!authHeader) {
      throw new AuthenticationError('No authorization header provided');
    }

    // Check if it's a Bearer token
    if (!authHeader.startsWith('Bearer ')) {
      throw new AuthenticationError('Invalid authorization header format. Expected: Bearer <token>');
    }

    // Extract the token
    const token = authHeader.substring(7);

    if (!token) {
      throw new AuthenticationError('No token provided');
    }

    // Allow development placeholder tokens generated by local auth service
    if (token.startsWith('supabase_jwt_')) {
      const parts = token.split('_');
      const userIdFromToken = parts.length >= 4 ? parts[2] : undefined;

      if (!userIdFromToken) {
        throw new AuthenticationError('Invalid development token format');
      }

      req.user = {
        id: userIdFromToken,
        email: undefined
      };
      req.userId = userIdFromToken;

      logger.debug('Development token accepted', { userId: userIdFromToken });
      return next();
    }

    // Verify token with Supabase
    const {
      data: { user },
      error,
    } = await supabase.auth.getUser(token);

    if (error) {
      logger.warn('Token verification failed', { error: error.message });
      throw new AuthenticationError('Invalid or expired token');
    }

    if (!user) {
      throw new AuthenticationError('User not found');
    }

    // Attach user to request
    req.user = {
      id: user.id,
      email: user.email,
    };
    req.userId = user.id;

    logger.debug('Token verified successfully', { userId: user.id });

    next();
  } catch (error) {
    if (error instanceof AuthenticationError) {
      res.status(error.statusCode).json({
        error: error.message,
        code: error.code,
      });
    } else {
      logger.error('Error in auth middleware', { error });
      res.status(401).json({
        error: 'Authentication failed',
        code: 'AUTH_ERROR',
      });
    }
  }
}

/**
 * Optional auth middleware - doesn't fail if no token provided
 * Useful for endpoints that work with or without authentication
 */
export async function optionalAuth(
  req: Request,
  res: Response,
  next: NextFunction
): Promise<void> {
  try {
    const authHeader = req.headers.authorization;

    if (!authHeader || !authHeader.startsWith('Bearer ')) {
      // No token provided, continue without auth
      return next();
    }

    const token = authHeader.substring(7);

    if (!token) {
      return next();
    }

    // Allow development placeholder tokens generated by local auth service
    if (token.startsWith('supabase_jwt_')) {
      const parts = token.split('_');
      const userIdFromToken = parts.length >= 4 ? parts[2] : undefined;

      if (userIdFromToken) {
        req.user = {
          id: userIdFromToken,
          email: undefined
        };
        req.userId = userIdFromToken;
      }

      return next();
    }

    // Try to verify token
    const {
      data: { user },
      error,
    } = await supabase.auth.getUser(token);

    if (!error && user) {
      req.user = {
        id: user.id,
        email: user.email,
      };
      req.userId = user.id;
    }

    next();
  } catch (error) {
    // Log error but don't fail the request
    logger.debug('Optional auth failed', { error });
    next();
  }
}

/**
 * Middleware to check if user has admin role
 * Must be used after verifyToken middleware
 */
export async function requireAdmin(
  req: Request,
  res: Response,
  next: NextFunction
): Promise<void> {
  try {
    if (!req.userId) {
      throw new AuthenticationError('User not authenticated');
    }

    // In a real app, you'd check the user's role from the database
    // For now, we'll just allow all authenticated users
    // TODO: Add admin role checking logic

    next();
  } catch (error) {
    if (error instanceof AuthenticationError) {
      res.status(error.statusCode).json({
        error: error.message,
        code: error.code,
      });
    } else {
      res.status(403).json({
        error: 'Admin access required',
        code: 'FORBIDDEN',
      });
    }
  }
}
